image: eosio/eosio-web-ide:v0.1.1

ports:
- port: 3000
  onOpen: ignore
- port: 8000
  onOpen: ignore
- port: 8080
  onOpen: ignore
- port: 8888
  onOpen: ignore
- port: 9876
  onOpen: ignore

tasks:
- before: cd webapp
  init: yarn
  command: nginx -c $PWD/nginx.conf; npx webpack-dev-server
- before: cleos wallet unlock --password </password
  command: nodeos --config-dir ~/eosio/chain/config --data-dir ~/eosio/chain/data -e -p eosio --plugin eosio::chain_api_plugin --contracts-console
